### PR TITLE
Revert back to use glide for vendor package update

### PR DESCRIPTION
**Pull request by zshi-redhat**
This PR reverts back to use glide for below consideration:
[Device Plugin API change](https://github.com/intel/sriov-network-device-plugin/pull/160) to support NUMA is blocked due to [issue](https://github.com/kubernetes/kubernetes/issues/82437), change back to glide allows us to have NUMA support be merged.

`go mod` support will be added later once we figure out how to resolve kubernetes package dependency with go module.

### CODE REVIEW

**Comment by cbf123** [comment]
I downloaded this branch and re-ran "glide update -v".  After that, "make test" worked.

**Comment by ahalim-intel** [comment]
@zshi-redhat Perhaps it's better to do a proper revert? Because even with this new changes(specially it changes the vendor again) the other PRs with vendor modification will have new conflicts. And it won't be easy to resolve those conflicts. Let's wait before we introduce/update or make any more changes in vendor until those PR's are merged?

**Comment by cbf123** [comment]
@ahalim-intel My PR https://github.com/intel/sriov-network-device-plugin/pull/160 is already rebased on this, but with another commit that re-runs "glide update -v" and updates the vendor code.

As we can see here, the checks are failing.  If I check out the code from this PR and run "glide update -v" then "make test" passes.

If you want to do a formal revert, it'd be no problem for me to rebase on top of that.

**Comment by zshi-redhat** [comment]
@ahalim-intel @cbf123 I can do a quick formal revert if you prefer to it.

**Comment by zshi-redhat** [comment]
Updated PR with `git revert`.

**Pull request merged**
