### PR TITLE
plugin watcher mode support

### LINKED ISSUE #60: adopt kubelet plugin watcher mode.
Refer to below link for Plugin Watcher design:
https://github.com/kubernetes/community/pull/2369

### PR DESCRIPTION
**Pull request by zshi-redhat**
Fixes #60

### CODE REVIEW

**Comment by ahalim-intel** [comment]
@zshi-redhat There's still build issue locally. If you can build this locally on your setup then I'd suggest add the glide.lock and vendor updates as part of this PR. Ideally, glide.yaml, glide.lock and vendor on a separate commit. We can squash them later when we merge it. Thanks

**Comment by zshi-redhat** [comment]
> @zshi-redhat There's still build issue locally. If you can build this locally on your setup then I'd suggest add the glide.lock and vendor updates as part of this PR. Ideally, glide.yaml, glide.lock and vendor on a separate commit. We can squash them later when we merge it. Thanks

sure, updated with two separate commits, one for glide update, the other for adding plugin watch.

**Comment by ahalim-intel** [comment]
> sure, updated with two separate commits, one for glide update, the other for adding plugin watch.

Thanks @zshi-redhat it builds now. However, it looks like glide.yaml is missing from the commit.

**Comment by zshi-redhat** [comment]
> > sure, updated with two separate commits, one for glide update, the other for adding plugin watch.
> 
> Thanks @zshi-redhat it builds now. However, it looks like glide.yaml is missing from the commit.

Added, thanks for capturing it!

**Comment by zshi-redhat** [comment]
updated to fix gofmt issue and add unit tests.

**Pull request merged**
