### PR TITLE
WIP: edited Dockerfiles and shellscript in line with static analysis

### PR DESCRIPTION
**Pull request by killianmuldoon**
Edited docker files and the entrypoint.sh shell script to meet static analysis directions from shellcheck(bash script) and Hadolint(Docker)

### CODE REVIEW

**Comment by zshi-redhat** [comment]
@killianmuldoon if that's commonly static analysis, do you think we could also add entry in Makefile and travis for future changes?

**Comment by killianmuldoon** [comment]
@zshi-redhat I WIPed this so we can have a discussion on what to include and what not in terms of the build pipeline - but I think it might be a good idea to have standardized linting for the additional scripts for sure

**Comment by ahalim-intel** [comment]
@killianmuldoon is this ready to merge?

**Comment by killianmuldoon** [comment]
Plan is now to rework this into two pull requests - one for Docker and one for shell so they can be considered separately.

**Pull request closed without merging**
