### PR TITLE
Documentation updated to refer to config map. Minor documentation fixes

### PR DESCRIPTION
**Pull request by killianmuldoon**
Added references to the config map rather than the config.json in the deployment instructions where appropriate. Some minor updates to capitalization and spelling.

### CODE REVIEW

**Comment by zshi-redhat** [comment]
@killianmuldoon do you know why the diff shows all lines in README.d are changed?

**Comment by killianmuldoon** [comment]
@zshi-redhat  Not sure exactly what happened there - it should be updated now.

**Comment by zshi-redhat** [comment]
> @zshi-redhat Not sure exactly what happened there - it should be updated now.

@killianmuldoon hi, do you mind resolve the conflict in the PR?

**Comment by zshi-redhat** [comment]
@killianmuldoon hi thanks for the update. It looks like there is still conflict after the update.
I can see the notification `This branch cannot be rebased due to conflicts`.

**Comment by killianmuldoon** [comment]
@zshi-redhat Can you see any details ? It's showing "This branch has no conflicts with the base branch" for me

**Comment by killianmuldoon** [comment]
@zshi-redhat I see now - the issue seems to be with rebase-and-merge. Is it okay to squash-and-merge here? I'm getting no issues for that on the Github UI

**Comment by zshi-redhat** [comment]
> @zshi-redhat I see now - the issue seems to be with rebase-and-merge. Is it okay to squash-and-merge here? I'm getting no issues for that on the Github UI

@killianmuldoon you may need to checkout a new branch from latest master and apply the change on top of it (this may require fix confliction), then force push the branch as `killianmuldoon:master` (I see the change is on master branch from your fork)

**Comment by ahalim-intel** [comment]
@killianmuldoon If you could fix the conflict now please that would be great. We have now merged all other pending PRs the README.

**Pull request merged**
