### PR TITLE
Replace '--resource-prefix' default value

### PR DESCRIPTION
**Pull request by adrianchiris**
This commit replaces the default value to be vendor agnostic
and updates relevant parts in README.

### CODE REVIEW

**Comment by zshi-redhat** [comment]
Most of the example yaml files under `deployment` and `doc` that using default resource prefix may also need to be changed.

**Comment by adrianchiris** [comment]
> Most of the example yaml files under deployment and doc that using default resource prefix may also need to be changed.

will update those as well

**Comment by adrianchiris** [comment]
As discussed in the bi-weekly meeting, this shall be deferred.

Repropose if/when this moves to a vendor neutral repository, possibly with a different URI.

**Comment by adrianchiris** [comment]
We should re-open this once the above occurs

**Pull request closed without merging**
