### PR TITLE
WIP: Add rdma device type support

### PR DESCRIPTION
**Pull request by Mmduh-483**
Signed-off-by: mamduhala <mamduhala@mellanox.com>

### CODE REVIEW

**Comment by zshi-redhat** [comment]
Did we have any discussion or conclusion on whether to support rdma as a new configurable option or new type? I saw there was an item in weekly resource management agenda, but no details.

**Comment by zshi-redhat** [comment]
Any thoughts of how rdma configuration might fit with the new selector approach? for example, could it be a new driver type?

**Comment by moshe010** [comment]
I not sure it fit driver, I was thinking to add selector of capabilities. I need to discuss this internally in mellanox . I hope to update on the next meeting

**Comment by zshi-redhat** [comment]
> I not sure it fit driver, I was thinking to add selector of capabilities. I need to discuss this internally in mellanox . I hope to update on the next meeting

Is mounting of "/dev/infiniband" the only requirement to use rdma devices in container?
If so, is it possible to automatically detect whether device supports rdma or not, and always mount "/dev/infiniband" during pod creation?

**Pull request closed without merging**
