### PR TITLE
update sample deployment manifests

### PR DESCRIPTION
**Pull request by ahalim-intel**
This update corrects the resource references that match with existing configMap.
Also fixes a problem where Network Status not being populated due to cniVersion was missing
for sriov network CRD.

Change-Id: I2ef7104ec3b94627698eb21b0708a79adcce7f59

### CODE REVIEW

**Comment by zshi-redhat** [comment]
@ahalim-intel  what about also changing the other two pods templates (pod-tc2.yaml, pod-tc3.yaml)?

**Comment by ahalim-intel** [comment]
> @ahalim-intel what about also changing the other two pods templates (pod-tc2.yaml, pod-tc3.yaml)?

Good question. The other 2 pods specs are same as pod-tc1.yaml, just wondering if we need them at all or can we just remove them?

**Comment by zshi-redhat** [comment]
> > @ahalim-intel what about also changing the other two pods templates (pod-tc2.yaml, pod-tc3.yaml)?
> 
> Good question. The other 2 pods specs are same as pod-tc1.yaml, just wondering if we need them at all or can we just remove them?

I sometime use them for multiple pod testing, for example, to check the network connectivity between two pods on same and different nodes. but this can be achieved by copying pod-tc1.yml.
so let's remove the same pod files, or maybe replace them with dpdk examples.

**Comment by ahalim-intel** [comment]
> I sometime use them for multiple pod testing, for example, to check the network connectivity between two pods on same and different nodes. but this can be achieved by copying pod-tc1.yml.
> so let's remove the same pod files, or maybe replace them with dpdk examples.

The dpdk example needs different configMap and net CRD. Let's keep the pod-tc2.yaml, with correct resource reference of course and remove other one.

**Comment by zshi-redhat** [comment]
> > I sometime use them for multiple pod testing, for example, to check the network connectivity between two pods on same and different nodes. but this can be achieved by copying pod-tc1.yml.
> > so let's remove the same pod files, or maybe replace them with dpdk examples.
> 
> The dpdk example needs different configMap and net CRD. Let's keep the pod-tc2.yaml, with correct resource reference of course and remove other one.

+1

**Pull request merged**
