### PR TITLE
Add arm64 build instructions and daemon set

### PR DESCRIPTION
**Pull request by AlexeyPerevalov**
Signed-off-by: Alexey Perevalov <alexey.perevalov@huawei.com>

### CODE REVIEW

**Comment by ahalim-intel** [comment]
Hi @AlexeyPerevalov, since this changes involved travis-ci changes, we are experiencing build delays issues lately due to our org travis-ci, we need to do an internal review of the impacts. 
Unfortunately we need to put this on hold for now.

If you like you can create a separate PR with the docker file only.

**Comment by AlexeyPerevalov** [comment]
Hello @ahalim-intel , I'll exclude .travis.yml from this commit. Also I found that that CI hooks ran when PR was created. I assumed docker push proceeded, but there is no nfvpe/sriov-device-plugin:arm64. Is it possible to submit image, avoiding travis?

**Comment by zshi-redhat** [comment]
> Hello @ahalim-intel , I'll exclude .travis.yml from this commit. Also I found that that CI hooks ran when PR was created. I assumed docker push proceeded, but there is no nfvpe/sriov-device-plugin:arm64. Is it possible to submit image, avoiding travis?

Image will only be pushed when PR gets merged.
PR creation will trigger travis CI for basic verficiation, but not pushing image.

**Comment by ahalim-intel** [comment]
@AlexeyPerevalov I think you it's good idea to add the dockerfile

**Comment by AlexeyPerevalov** [comment]
@zshi-redhat @ahalim-intel is possible to merge .travis with arm and all other necessary files just to make docker push and then revert just .travis file to release travis?

**Comment by zshi-redhat** [comment]
@AlexeyPerevalov I noticed that the arm64 daemonset is using image `alexeyperevalov/arm64-sriov-device-plugin`, is this available publicly and how would it be updated if there is new code change?
I understand we may not be adding it in travis build and push it automatically until we change to github actions.  but would like to know how it will be updated with latest changes.

**Comment by ahalim-intel** [comment]
> @AlexeyPerevalov I noticed that the arm64 daemonset is using image `alexeyperevalov/arm64-sriov-device-plugin`, is this available publicly and how would it be updated if there is new code change?
> I understand we may not be adding it in travis build and push it automatically until we change to github actions. but would like to know how it will be updated with latest changes.

This is temporary solution. I believe the image will be kept up to date in their own environment for now.

**Comment by zshi-redhat** [comment]
> > @AlexeyPerevalov I noticed that the arm64 daemonset is using image `alexeyperevalov/arm64-sriov-device-plugin`, is this available publicly and how would it be updated if there is new code change?
> > I understand we may not be adding it in travis build and push it automatically until we change to github actions. but would like to know how it will be updated with latest changes.
> 
> This is temporary solution. I believe the image will be kept up to date in their own environment for now.

ok, maybe add a TODO comment in the file?

**Comment by AlexeyPerevalov** [comment]
> > > @AlexeyPerevalov I noticed that the arm64 daemonset is using image `alexeyperevalov/arm64-sriov-device-plugin`, is this available publicly and how would it be updated if there is new code change?
> > > I understand we may not be adding it in travis build and push it automatically until we change to github actions. but would like to know how it will be updated with latest changes.
> > 
> > 
> > This is temporary solution. I believe the image will be kept up to date in their own environment for now.
> 
> ok, maybe add a TODO comment in the file?
done

**Pull request merged**
