### PR TITLE
Add mutating admission controller

### PR DESCRIPTION
**Pull request by przemeklal**
* Read pod spec, look for network annotations - if present ask API server if there's any resource associated with the network
* Inject resources requests/limits into first container in the spec for all network annotations that use them
* In case of errors block creation of given pod
* Add code for automated deployment of required resources designed to run as a Job
* Add tests for various mutation functionalities
* Build Docker image with webhook server and webhook installer applications
* Update documentation with installation steps
* Add Kubernetes job specification for automated creation of certificates, secret, service and webhook configs
* Add deployment specification for running webhook server

### CODE REVIEW

**Comment by przemeklal** [comment]
@zshi-redhat Sounds good to me, but it would be good to get some input from @rkamudhan on this idea.

**Comment by przemeklal** [comment]
Hey @ahalim-intel, as per our discussion I updated the webhook's Dockerfile to use multi-stage build, now the resulting image is ~67MB instead of 1.4GB, so that should be more acceptable now

**Comment by ahalim-intel** [comment]
@zshi-redhat 

> One general comment: can we put this SR-IOV webhook support in a separate repo under Intel github org? This will make it easier later when we want to move the webhook in NPWG like multus did.

This is a important component for sriov-device-plugin. This allows user not to provide explicit resource request for sriov VFs which could be error-prone. Yet another repository is  long-shot for many reason. Lets maintain this code here as this enhances the sriov-device-plugin deployment.

@przemeklal We need some documentations pointing to the example deployments and some basic howto's.

**Comment by zshi-redhat** [comment]
> @zshi-redhat
> 
> > One general comment: can we put this SR-IOV webhook support in a separate repo under Intel github org? This will make it easier later when we want to move the webhook in NPWG like multus did.
> 
> This is a important component for sriov-device-plugin. This allows user not to provide explicit resource request for sriov VFs which could be error-prone. Yet another repository is long-shot for many reason. Lets maintain this code here as this enhances the sriov-device-plugin deployment.

Ok, let's maintain it here and plan on the separate repo.

> 
> @przemeklal We need some documentations pointing to the example deployments and some basic howto's.

**Comment by zshi-redhat** [comment]
Some minor issues with unit tests below: Run ``make test``, got errors:

# github.com/intel/sriov-network-device-plugin/pkg/webhook
pkg/webhook/webhook_test.go:101:5: undefined: ValidateHandler
pkg/webhook/webhook_test.go:112:5: undefined: ValidateHandler
pkg/webhook/webhook_test.go:123:5: undefined: ValidateHandler
pkg/webhook/webhook_test.go:132:22: undefined: validateNetworkAttachmentDefinition
FAIL	github.com/intel/sriov-network-device-plugin/pkg/webhook [build failed]
Makefile:97: recipe for target 'test' failed
make: *** [test] Error 2

**Comment by zshi-redhat** [comment]
Tried to run the webhook on a kube-1.12 environment, got following error when re-creating the webhook installer and server:

```
I1227 21:12:34.208516       1 main.go:34] starting mutating admission controller for network resources injection
F1227 21:12:34.212742       1 main.go:45] error starting web server: tls: private key does not match public key
```

It seems that the newly created private key in the second run doesn't work with already existing CSR which is created in the first run. Maybe we shall re-create the CSR every time when webhook installer is invoked just like how webhook service and webhook config are dealt with.

**Comment by zshi-redhat** [comment]
Thanks for the unit test fixes, it works.

**Comment by przemeklal** [comment]
Hey @zshi-redhat I also added a small fix to always recreate certificates during webhook installation, hope it helps.

**Comment by zshi-redhat** [comment]
> Hey @zshi-redhat I also added a small fix to always recreate certificates during webhook installation, hope it helps.

Thanks for the update, @przemeklal !
Confirmed that CSR be created every time when webhook_installer is invoked,  no tls mismatch observed.

**Comment by przemeklal** [comment]
@zshi-redhat @rkamudhan @ahalim-intel hey guys, are there any plans yet where this code is going to end up?

**Comment by zshi-redhat** [comment]
> @zshi-redhat @rkamudhan @ahalim-intel hey guys, are there any plans yet where this code is going to end up?

I thought the plan was to have a new repo under intel domain for sriov admission controller or webhook, and then seeking to move it somewhere under CNCF if not K8sNetworkPlumbingWG? There was a repo created for sriov admission controller under K8sNetworkPlumbingWG but [this](https://github.com/K8sNetworkPlumbingWG/sriov-dp-admission-controller) was discussed not a good idea.

**Comment by zshi-redhat** [comment]
> > @zshi-redhat @rkamudhan @ahalim-intel hey guys, are there any plans yet where this code is going to end up?
> 
> I thought the plan was to have a new repo under intel domain for sriov admission controller or webhook, and then seeking to move it somewhere under CNCF if not K8sNetworkPlumbingWG? There was a repo created for sriov admission controller under K8sNetworkPlumbingWG but [this](https://github.com/K8sNetworkPlumbingWG/sriov-dp-admission-controller) was discussed not a good idea.

@rkamudhan @ahalim-intel any update or suggestions?

**Comment by przemeklal** [comment]
Hey @ahalim-intel @zshi-redhat @booxter
PR with this feature created in a new repository under Intel organization available here: https://github.com/intel/network-resources-injector/pull/1

**Pull request closed without merging**
