### PR TITLE
Add support to pfNames selector with VF range and list

### PR DESCRIPTION
**Pull request by rorysexton**
"pfNames": ["ens2f1#0,2-4,7"] - use VF's 0,2-4 and 7 of PF ens2f1
This adds to the flexibility of the pfNames selector and also maintains all backwards compatibility with existing configurations.

### CODE REVIEW

**Comment by killianmuldoon** [comment]
Thanks for this Pr - looks like a useful addition. Could you add unit tests to verify?

**Comment by rorysexton** [comment]
Added unit tests in second commit

**Comment by ahalim-intel** [comment]
Hi @rorysexton,
This looks good to me. If you could update the main [README.md](https://github.com/intel/sriov-network-device-plugin#assumptions) with new format of "pfNames" that would be great.

**Comment by rorysexton** [comment]
Updated README.md in latest commit

**Pull request merged**
